version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8002:80"
        volumes:
            - ./:/var/www/html/
        networks:
            - default
volumes:
    persistent: